"""Make player IDs nullable for guest games

Revision ID: 26b136ecf4ca
Revises: 56f4622528eb
Create Date: 2025-09-03 14:00:03.537617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b136ecf4ca'
down_revision: Union[str, Sequence[str], None] = '56f4622528eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chess_games', 'white_player_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chess_games', 'black_player_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chess_games', 'black_player_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chess_games', 'white_player_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
