"""Make elo column nullable

Revision ID: 42aafc3b0ce3
Revises: a7237e3cad8e
Create Date: 2025-08-16 15:31:24.248148

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42aafc3b0ce3'
down_revision: Union[str, Sequence[str], None] = 'a7237e3cad8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'elo', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'elo', server_default='1200')
    # ### end Alembic commands ###
