"""Remove unused fields from refresh_tokens table

Revision ID: 53a8280500ed
Revises: 87d62e3284c9
Create Date: 2025-08-19 13:25:31.614044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53a8280500ed'
down_revision: Union[str, Sequence[str], None] = '87d62e3284c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'picture')
    op.drop_column('refresh_tokens', 'name')
    op.drop_column('refresh_tokens', 'google_access_token')
    op.drop_column('refresh_tokens', 'email')
    op.drop_column('refresh_tokens', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('refresh_tokens', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('google_access_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('refresh_tokens', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
