"""add_last_activity_at_to_users

Revision ID: 56f4622528eb
Revises: 4549b0ad20e0
Create Date: 2025-09-03 08:35:02.592673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f4622528eb'
down_revision: Union[str, Sequence[str], None] = '4549b0ad20e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_last_activity_at'), 'users', ['last_activity_at'], unique=False)
    # ### end Alembic commands ###
    
    # Populate existing data: set last_activity_at = created_at for existing users
    op.execute("UPDATE users SET last_activity_at = created_at WHERE last_activity_at IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_activity_at'), table_name='users')
    op.drop_column('users', 'last_activity_at')
    # ### end Alembic commands ###
