"""add_end_reason_to_chess_games

Revision ID: 682092742fe1
Revises: 53a8280500ed
Create Date: 2025-08-21 07:08:39.872552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682092742fe1'
down_revision: Union[str, Sequence[str], None] = '53a8280500ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chess_games', sa.Column('end_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chess_games', 'end_reason')
    # ### end Alembic commands ###
