"""Add elo field to users table

Revision ID: a7237e3cad8e
Revises: e7c09e5eb722
Create Date: 2025-08-16 15:29:09.808684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a7237e3cad8e'
down_revision: Union[str, Sequence[str], None] = 'e7c09e5eb722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('elo', sa.Integer(), nullable=True, server_default='1200'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'elo')
    # ### end Alembic commands ###
