"""add chess game model

Revision ID: ca5e4b6ce112
Revises: 42aafc3b0ce3
Create Date: 2025-08-17 20:55:03.393737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5e4b6ce112'
down_revision: Union[str, Sequence[str], None] = '42aafc3b0ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chess_games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('white_player_id', sa.String(), nullable=False),
    sa.Column('black_player_id', sa.String(), nullable=False),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['white_player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chess_games')
    # ### end Alembic commands ###
