name: Deploy to Linode

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Linode
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          script: |
            set -e

            echo "Starting deployment process..."

            # Navigate to app directory (adjust path as needed)
            echo "Navigating to application directory..."
            cd ~/chess-cg

            # Pull latest changes
            echo "Pulling latest changes from the main branch..."
            git pull origin main

            # Navigate to backend directory
            echo "Navigating to backend directory..."
            cd backend

            # Install/update dependencies
            echo "Installing/updating dependencies..."
            ~/.local/bin/uv sync

            # Stop existing server if running
            echo "Stopping existing server if running..."
            if [ -f ~/chess-cg-server.pid ]; then
              PID=$(cat ~/chess-cg-server.pid)
              if kill -0 "$PID" 2>/dev/null; then
                echo "Stopping process $PID"
                kill "$PID"
                sleep 3
                if kill -0 "$PID" 2>/dev/null; then
                  echo "Process still running, force killing"
                  kill -9 "$PID"
                fi
              fi
              rm -f ~/chess-cg-server.pid
            else
              echo "No PID file found."
            fi

            # Update nginx configuration
            echo "Updating nginx configuration..."
            sudo cp ../nginx.conf /etc/nginx/sites-available/chess-cg
            sudo ln -sf /etc/nginx/sites-available/chess-cg /etc/nginx/sites-enabled/chess-cg

            # Test nginx configuration
            echo "Testing nginx configuration..."
            sudo nginx -t

            # Reload nginx
            echo "Reloading nginx..."
            sudo systemctl reload nginx

            # Start the backend server in background with PID tracking
            echo "Starting the backend server..."
            nohup ~/.local/bin/uv run fastapi run app/main.py --host 0.0.0.0 --port 8000 > ~/chess-cg-server.log 2>&1 &
            echo $! > ~/chess-cg-server.pid

            echo "Deployment completed successfully"
